### PR TITLE
Test/assignment

### PR DESCRIPTION
**Pull request by eichelbw**
WIP, feedback/don't merge

things in this pr so far
- assignment group controller tests
- assignment group controller changes to make those tests pass
- assignment group model tests
- fixtures
- deletion of a whole bunch of outdated tests

### CODE REVIEW

**Comment by hattwj** [comment]
Awesome! This rocks!

**Comment by hattwj** [comment]
We do have factoryGirl for fixtures if you are interested

**Comment by eichelbw** [comment]
i hadn't used minitest before this project, and one of the first articles i came across was [this one](http://brandonhilkert.com/blog/7-reasons-why-im-sticking-with-minitest-and-fixtures-in-rails/), which also suggests using rails fixtures over factorygirl. 

do you hold the opposite opinion? i'm definitely wiling to defer to your experience if you've used both and feel that FG is the better option.

**Comment by hattwj** [comment]
While I am partial for FactoryGirl I dont think we need to change anything. You already have a fair amount of work done with the default fixtures which is nice. There are some things that factoryGirl and Faker can do that cannot be accomplished otherwise. I mostly just wanted to mention it, because of its flexibility. Maybe keep things the way they are. Would you be comfortable having both of them in the code base? Maybe we could do that.
-wjh

```
On Wednesday, February 3, 2016 9:04 AM, William Eichelberger <notifications@github.com> wrote:
```

 i hadn't used minitest before this project, and one of the first articles i came across was this one, which also suggests using rails fixtures over factorygirl. do you hold the opposite opinion? i'm definitely wiling to defer to your experience if you've used both and feel that FG is the better option.—

**Comment by eichelbw** [comment]
that could work. i'll also do some reading and see if i can convince myself that switching fully to factorygirl is the better option.

**Pull request closed without merging**
